version: '3'
services:
  web:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/031_test_Fevernova_BMAT_Spain
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sv
      - POSTGRES_PASSWORD=sv
      - POSTGRES_DB=sv
volumes:
  postgres_data:
